apiVersion: v1
kind: Service
metadata:
  name: siddikconnect
  namespace: siddikconnect
  labels:
    app: siddikconnect
spec:
  type: NodePort
  selector:
    app: siddikconnect
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080